# Generated by Django 4.2.5 on 2026-03-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
        ('notifications', '0003_notification_created_by_notification_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organizations.organization'),
        ),
    ]
