# Generated by Django 4.2.5 on 2026-02-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_created_by_organization_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
