# Generated by Django 4.2.5 on 2026-03-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_alter_userrole_role_alter_userrole_user'),
        ('organizations', '0006_alter_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_logos', to='access.image'),
        ),
    ]
