# Generated by Django 4.2.5 on 2026-02-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_userrole_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
