# Generated by Django 4.2.5 on 2026-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_auditlog_created_by_auditlog_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
