# Generated by Django 4.2.5 on 2026-02-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
