# Generated by Django 4.2.5 on 2026-03-04 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_migrated_courses_v2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='courses_category',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses_course',
        ),
        migrations.AlterModelTable(
            name='courseskill',
            table='courses_courseskill',
        ),
        migrations.AlterModelTable(
            name='learningpath',
            table='courses_learningpath',
        ),
        migrations.AlterModelTable(
            name='learningpathcourse',
            table='courses_learningpathcourse',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='courses_lesson',
        ),
        migrations.AlterModelTable(
            name='organizationcourse',
            table='courses_organizationcourse',
        ),
        migrations.AlterModelTable(
            name='section',
            table='courses_section',
        ),
        migrations.AlterModelTable(
            name='skill',
            table='courses_skill',
        ),
        migrations.AlterModelTable(
            name='video',
            table='courses_video',
        ),
    ]
