# Generated by Django 4.2.5 on 2026-03-04 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_logo'),
        ('access', '0016_department_enrollment_userdepartment_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_token',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='courseprogress',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='lessonprogress',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_time_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
