# Generated by Django 4.2.5 on 2026-03-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0017_remove_certificate_certificate_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('organization_admin', 'Organization Admin'), ('organization_user', 'Organization User')], default='organization_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
