# Generated by Django 4.2.5 on 2026-03-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_logo'),
        ('access', '0018_user_role_alter_user_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('organization_admin', 'Organization Admin'), ('organization_user', 'Organization User')], max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization'),
        ),
    ]
