# Generated by Django 4.2.5 on 2026-03-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
        ('quizzes', '0003_rename_start_time_quizattempt_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='organizations.organization'),
        ),
    ]
