# Generated by Django 4.2.5 on 2026-03-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
        ('courses', '0003_rename_assigned_at_organizationcourse_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='skill',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
