# Generated by Django 4.2.5 on 2026-03-04 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_created_at_department_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdepartment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdepartment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserDepartment',
        ),
    ]
